version: '3.3'

services:
  backend:
    build:
      context: .
      args:
        MIX_ENV: "prod"
    stdin_open: true
    ports:
      - 5001:5001
      - 5002:5002
      - 5003:5003
      - 5004:5004/udp
      - 5005:5005
      - 5006:5006