version: '3.3'

services:
  backend:
    build:
      context: .
      args:
        MIX_ENV: "prod"
    stdin_open: true
    ports:
      - "5010:5010"
      - "5020:5020"
      - "5030:5030"
      - "5040:5040"
      - "5050:5050"
      - "6000:6000/udp"